spring:
  config:
    activate:
      on-profile: dev
  server:
    port: 9000
  datasource:
    url: jdbc:postgresql://localhost:5432/gym
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
main:
  allow-circular-references: true
management:
  endpoint:
    health:
      db:
        enabled: true
      defaults:
        enabled: true
      diskspace:
        enabled: true
      show-details: "always"
  endpoints:
    web:
      exposure:
        include: "*"